package com.example.emaildemo;

import java.util.Properties;

import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

public class Test {

	public static void main(String[] args) {

		String to = "akula.veerraju@incture.com";

		final String username = "laxmimb235@gmail.com";

		final String password = "laxmi1234";

		Properties props = new Properties();

		props.put("mail.smtp.auth", "true");

		props.put("mail.smtp.starttls.enable", "true");

		if (to.contains("@") && to.contains(".com"))

			if (!username.contains("gmail.com"))

				props.put("mail.smtp.host", "smtp.office365.com"); // if sender
			// uses
			// microsoft
			// mail

			else

				props.put("mail.smtp.host", "smtp.gmail.com"); // if sender
		// using
		// gmail.com

		props.put("mail.smtp.port", "587");

		Session session = Session.getInstance(props, new javax.mail.Authenticator() {

			protected PasswordAuthentication getPasswordAuthentication() {

				return new PasswordAuthentication(username, password);

			}

		});

		try {

			Message message = new MimeMessage(session);

			message.setFrom(new InternetAddress(username)); // senders id

			// address

			message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to)); // to//
																						// id

			// address

			message.setSubject("Purchase Request Application");

			Multipart multipart = new MimeMultipart();

			BodyPart messageBodyPart = new MimeBodyPart(); // 1st object

			String s1 = "https://vendormanagement2-kbniwmq1aj.dispatcher.hana.ondemand.com/index.html?hc_reset&vendorId=";

			String s4 = "This is Autogenerated e-mail and may contain confidential or privileged information for the intended recipient (s). If you are not the intended recipient, please do not use or disseminate the information, notify the sender and delete it permanently.";

			messageBodyPart.setText("\nClick on the URL:-\n" + s1 + " \n \n " + s4 + "\n");

			multipart.addBodyPart(messageBodyPart);

			// Send the complete message parts

			message.setContent(multipart);

			Transport.send(message);
			System.out.println("success");

		} catch (Exception e) {

			System.err.println("Exception:-" + e.getMessage());

		}

	}

}
